# Generated by Django 4.0.5 on 2022-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_shorted_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shorted_link',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
