# Generated by Django 4.0.5 on 2022-06-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_alter_link_main_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shorted_link',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
