# Generated by Django 4.0.5 on 2022-06-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='main_link',
            field=models.URLField(max_length=250),
        ),
    ]
